Script started on 2015年03月16日 (週一) 12時26分11秒
]0;F74031166@2015cpp: ~/lab1F74031166@2015cpp:~/lab1$ whoami; pwd
F74031166
/home/F74031166/lab1
]0;F74031166@2015cpp: ~/lab1F74031166@2015cpp:~/lab1$  git config ‐l[C[1Pl[1Pl-l[C
git: 'config-l' is not a git command. See 'git --help'.
]0;F74031166@2015cpp: ~/lab1F74031166@2015cpp:~/lab1$ whoami; pwdgit clone https://github.com/F74031166/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cwhoami; pwd[K[Kgit config -l
user.name=F74031166
user.mail=sasakikojilou@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.lab1.url=https://github.com/F74031166/lab1.git
remote.lab1.fetch=+refs/heads/*:refs/remotes/lab1/*
remote.lab2.url=https://github.com/F74031166/lab1.git
remote.lab2.fetch=+refs/heads/*:refs/remotes/lab2/*
remote.lab.url=https://github.com/F74031166/lab1.git
remote.lab.fetch=+refs/heads/*:refs/remotes/lab/*
]0;F74031166@2015cpp: ~/lab1F74031166@2015cpp:~/lab1$ git clone https://github.com/F74031166/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;F74031166@2015cpp: ~/lab1F74031166@2015cpp:~/lab1$ exit

Script done on 2015年03月16日 (週一) 12時27分14秒
